baseURL = "https://bulldogbolivia.netlify.com"
languageCode = "es"
theme = "security-company"
title = "Bulldog Security"
[params]
address = "Av. Alemana # 3265"
companyName = "Bulldog Security"
description = "Seguridad electronica"
email = "gerencia@bulldogbolivia.com"
location = "Santa Cruz - Bolivia"
mobilePhone = "+591 69154634"
phone = "3 254014"
location  = "Santa Cruz - Bolivia"
facebookURL = "https://www.facebook.com/pg/BullDogSeguridadElectronica"
instagramURL = "https://www.instagram.com/cctv_latino"
